=== awillis/sozu/schema/template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" vc:minVersion="1.1"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    xmlns:tt="http://schema.amekoshi.com/2020/12/tmt/template"
    xmlns:abs="http://schema.amekoshi.com/2020/12/tmt/abstract"
    targetNamespace="http://schema.amekoshi.com/2020/12/tmt/template">
    <import namespace="http://schema.amekoshi.com/2020/12/tmt/abstract"
        schemaLocation="abstract.xsd"/>
    <element name="process" substitutionGroup="abs:TemplateStencil">
        <complexType>
            <complexContent>
                <extension base="abs:templateStencilType"/>
            </complexContent>
        </complexType>
    </element>
    <element name="function" substitutionGroup="abs:TemplateStencil">
        <complexType>
            <complexContent>
                <extension base="abs:templateStencilType"/>
            </complexContent>
        </complexType>
    </element>
    <element name="datastore" substitutionGroup="abs:TemplateStencil">
        <complexType>
            <complexContent>
                <extension base="abs:templateStencilType"/>
            </complexContent>
        </complexType>
    </element>
    <element name="dataflow" substitutionGroup="abs:TemplateStencil">
        <complexType>
            <complexContent>
                <extension base="abs:templateStencilType"/>
            </complexContent>
        </complexType>
    </element>
    <element name="boundary" substitutionGroup="abs:TemplateStencil">
        <complexType>
            <complexContent>
                <extension base="abs:templateStencilType">
                    <sequence>
                        <element name="type">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="line"/>
                                    <enumeration value="rectangle"/>
                                    <enumeration value="ellipse"/>
                                </restriction>
                            </simpleType>
                        </element>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
    </element>
    <element name="rule">
        <complexType>
            <sequence>
                <element ref="abs:name"/>
                <element name="description" type="string"/>
                <element name="filter" type="string">
                    <annotation>
                        <documentation>Filter to be applied to stencil attributes. If a match is
                            found, the threat should be regarded as valid for a given
                            model.</documentation>
                    </annotation>
                </element>
            </sequence>
            <attribute name="stencil_id" type="abs:id" use="required"/>
            <attribute name="threat_id" type="abs:id" use="required"/>
        </complexType>
    </element>
    <element name="threat">
        <complexType>
            <sequence>
                <element ref="abs:name"/>
            </sequence>
            <attribute name="threat_id" type="abs:id" use="required"/>
        </complexType>
    </element>
    <complexType name="stencilList">
        <sequence maxOccurs="unbounded">
            <element ref="abs:TemplateStencil"/>
        </sequence>
    </complexType>
    <complexType name="ruleList">
        <sequence maxOccurs="unbounded">
            <element ref="tt:rule"/>
        </sequence>
    </complexType>
    <complexType name="threatList">
        <sequence maxOccurs="unbounded">
            <element ref="tt:threat"/>
        </sequence>
    </complexType>
    <group name="metadata">
        <sequence>
            <element name="author" type="string"/>
            <element name="id" type="ID"/>
            <element name="name" type="string"/>
            <element name="version" type="positiveInteger"/>
        </sequence>
    </group>
    <group name="template">
        <sequence>
            <group ref="tt:metadata"/>
            <element name="stencils" type="tt:stencilList">
                <unique name="uniqueStencil">
                    <selector xpath="abs:TemplateStencil"/>
                    <field xpath="@stencil_id"/>
                </unique>
            </element>
            <element name="ruleset" type="tt:ruleList">
                <unique name="uniqueRule">
                    <selector xpath="tt:rule"/>
                    <field xpath="@stencil_id"/>
                    <field xpath="@threat_id"/>
                </unique>
            </element>
            <element name="threats" type="tt:threatList">
                <unique name="uniqueThreat">
                    <selector xpath="tt:threat"/>
                    <field xpath="@threat_id"/>
                </unique>
            </element>
        </sequence>
    </group>
    <element name="template">
        <complexType>
            <group ref="tt:template"/>
        </complexType>
    </element>
</schema>

=== awillis/sozu/schema/template1.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns="http://schema.amekoshi.com/2020/12/tmt/template"
 xmlns:abs="http://schema.amekoshi.com/2020/12/tmt/abstract"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://schema.amekoshi.com/2020/12/tmt/template file:/C:/Users/alan/PycharmProjects/sozu/schema/template.xsd">
    <author>R1YrkgLnZrqT</author>
    <id>ID000</id>
    <name>Jzlxdg38VEnvovx</name>
    <version>1809845359</version>
    <stencils>
        <stencil type="process" id="Bb43ffA0-ba0A-8edD-DB8F-aa4eEDA787bb">
            <abs:name>wwwoo</abs:name>
            <abs:description>W1bp-22YZYYnd.cVNCkjhm8kW</abs:description>
            <abs:image>696670877170668477856966888973788768879065837188</abs:image>
        </stencil>
        <stencil type="boundary" id="67C26fbE-86FD-D3F4-CAe8-CbAD9CCaBedC">
            <abs:name>P2P.2p_rPeyelfWp-tL.Qzfba_lKO36</abs:name>
            <abs:description>NEJQGyeO1Eihza</abs:description>
            <abs:image>678784778285738167896766747578817386848887836980707584897676676586716681</abs:image>
            <type>line</type>
        </stencil>
    </stencils>
    <ruleset>
        <rule stencil="Afdabaee-3DeC-7EfA-a8Ab-caf7f78b60De" threat="Bddde1d7-b36D-0CbA-BACa-2A16DfCfBAEf">
            <name>bQUGqZcwHsUl11rAc2gZMa395tXp.sThj1hA9Ic</name>
            <description>u6</description>
            <filter>gB_xelYNWl2Spn-FchD1OPX.GJv</filter>
        </rule>
        <rule stencil="CeBB9b2A-B71C-eae4-fDd0-FaDDeBC4Aabd" threat="D0AeaDBd-1BAa-e6D6-2Cfe-E0DfbFed3c0c">
            <name>Rjk1</name>
            <description>Zbeywwm3XhwDWMBTvId6Cvt_Xqtn-</description>
            <filter>p8</filter>
        </rule>
    </ruleset>
    <threats>
        <threat id="ED196F6F-AAeb-7FDc-CBCA-838DAeBeb96F">
            <name>kkbCpRDPpNL</name>
        </threat>
        <threat id="A7Bd2CF8-aCa9-2D3A-Ee35-08B49c8bFaac">
            <name>jwAN6jgHMS.</name>
        </threat>
    </threats>
</template>
